apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-test
  namespace: jenkins-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-test
  template:
    metadata:
      labels:
        app: jenkins-test
    spec:
      containers:
      - name: jenkins-test-app
        image: beatrueman/ci:2.0
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-test-svc
  namespace: jenkins-project
spec:
  selector:
    app: jenkins-test
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30002
  type: NodePort
